### ISSUE TITLE
Multi-word, kebab-cased font variables get camel-cased

### ISSUE THREAD

**Issue by andytron** [innocenzi/tailwindcss-theming#24] opened 2020-05-28 16:34 UTC
Thanks for creating the plugin!

So in the `v3.0.0-beta.0` release (I haven't tried and don't plan on testing this in any older version of the plugin), when I try to use a multi-word, kebab-cased font variable name in my `theme.config.js`, it gets outputted in Tailwind as a camel-cased variable name after the `font-` prefix.

E.g.: `.setVariable('sans-serif', ['Inter', 'Segoe UI', 'Roboto'], 'fontFamily')` gets exported as `font-sansSerif`, when my original intent is to create a `font-sans-serif` class.

Would you be able to confirm if this is intended behavior, and if there would be any considerations for supporting/preserving kebab-cased variable names?

**Comment by innocenzi** [comment] 2020-05-28 17:35
Hey, this is not intended behavior, the opposite is actually supposed to happen. I'll check that out tonight. Thanks!

**Comment by innocenzi** [comment] 2020-05-28 18:25
This should be fixed in the [new version](https://github.com/innocenzi/tailwindcss-theming/releases/tag/v3.0.0-beta.1)

**Closed by innocenzi** 2020-05-28 18:25 UTC
Labels: bug
